name: 'medicare_lds_connector'
version: '0.1.1'
config-version: 2

profile: default                   

vars:
  input_database: ffs_all
  input_schema:  raw_data
  debug_mode: false
  claims_enabled: true
  cms_hcc_payment_year: 2019
  years: 2018,2019
  patient_id_suffix: "{{ env_var('DECI_RUN', 's') }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  models:
  medicare_lds_connector:
    +bind: false
    +materialized: table
    +schema: staging
    staging:
      +materialized: table
